import Head from "next/head";
import { Link } from '@chakra-ui/next-js'
import { Button, ButtonGroup } from '@chakra-ui/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        hello world
        <Link href='/about' color='blue.400' _hover={{ color: 'blue.500' }}>
          About
        </Link>
        <Button colorScheme='blue'>Button</Button>
      </main>
    </>
  );
}
